### ISSUE TITLE
How to set logging level in restito's StubServer?

### ISSUE THREAD

**Issue by IvanFernandez** [mkotsur/restito#14]
Hi,

is there any choice to show/hide restito's StubServer logs. I have tried it modifying my log4j.properties file, but it doesn't work

**Comment by sverhagen** [comment]
dec 11, 2013 5:32:39 PM org.glassfish.grizzly.http.server.NetworkListener start
    Information: Started listener bound to [0.0.0.0:8093]

Messages like these actually come from Restito using Grizzly which uses `java.util.logging`, essentially its own logging backend. You can configure it in a number of ways. My choice is to use this ahead of tests that use Restito:

    import java.util.logging.LogManager;
    ...
    LogManager.getLogManager().reset();
