### ISSUE TITLE
Add GET/POST parameter matching #loprio

### ISSUE THREAD

**Issue by nfx** [mkotsur/restito#21]
In some cases it's easier to make stubs based on parameters as well - 

````
blah.match(get("/file/report").withQueryParam("id", "aaa"))
                .then(ok(), resourceContent("..."));
blah.match(get("/file/report").withQueryParam("id", "bbb"))
                .then(notFound());
````

Of course, it doesn't make much sense to do this before #19 is implemented, as there could be some running time benefit when rule would be started on class level and not for every test in 30-case test suite.

**Comment by mkotsur** [comment]
Actually, this is already possible:

```
whenHttp(server).
                match(get("/demo"), parameter("id", "aaa")).
                then(status(HttpStatus.OK_200));

whenHttp(server).
                match(get("/demo"), parameter("id", "bbb")).
                then(status(HttpStatus.OK_200));
```

Sorry for the late reply :-)
