### ISSUE TITLE
improve charset indication of return type

### ISSUE THREAD

**Issue by garretwilson** [mkotsur/restito#24]
The restito approach for indicating the charset of an HTTP response is convoluted and confusing.

Let's say I have a custom file format call the Foo Format. It is based upon XML, but it has its own MIME type and an extension `.foo`.

Strangely, here is the only way that I've been able to correctly return a foo file:

	...
	then(ok(),
	    charset(UTF_8.toString()),
	    contentType(FOO_MIME_TYPE),
	    resourceContent(fooFileURL, UTF_8.toString())

First of all, I don't understand why I need to specify the charset when I call `resourceContent()`. Even though this file is to be interpreted as UTF-8 when parsed, at the HTTP level it should be sent back as binary. As long as the HTTP response indicates UTF-8, then it is up to the client to recognize the charset and use that to parse the entity. In other words, why is restito parsing my resource? Restito should simply send back the bytes.

Secondly, if restito feels it has to parse my resource, why do I need to specify it again? Didn't I already indicate a `charset()` of UTF-8? Why do I need to specify it twice?

Another odd thing: if I put the `charset()` designation at the end, it doesn't work. Why does the order matter?

Note also that `charset(String)` should accept an actual `Charset` instance, e.g. `charset(java.nio.charset.CharSet)`. This class has been around since Java 1.4. That way I can use. e.g. `java.nio.charset.StandardCharsets.UTF_8`, introduced in Java 7.

Similarly it would be nice if `contentType(String)` would support the JAX-RS `javax.ws.rs.core.MediaType` class.

Lastly I need a way to associate MIME types and charsets with extensions. If I were to simply associate the `FOO_MIME_TYPE` with the `.foo` extension, then I could simply use `contentType(FOO_MIME_TYPE)` and all the above would be taken care of for me.

**Comment by mkotsur** [comment]
> Charset in `resourceContent()` is used only to parsed the resource

I agree here. Now the parameter becomes deprecated. The recommended way is: 
```
then(
   charset(UTF_16),
   resourceContent("content.cst"),
   contentType("application/text")
)
```

> if I put the charset() designation at the end, it doesn't work. Why does the order matter

Fixed that. It has to do with the internals of grizzly, default encodings and so on. Please take a look at the source code for more details. The most important - it works now :-)

> Similarly it would be nice if contentType(String) would support the JAX-RS javax.ws.rs.core.MediaType class.

Good point. I've created an alias.

**Comment by mkotsur** [comment]
It appears to be that `javax.ws.rs` is not a part of JVM, so for that method an external dependency needed, which I don't really want to add. Strangely the tests ran ok on my laptop, but failed on CloudBees Jenkins with `error: package javax.ws.rs.core does not exist`. Removing that method for now.
