### ISSUE TITLE
Support java 6 in newer versions

### ISSUE THREAD

**Issue by sandro-csimas** [mkotsur/restito#26]
Hi, i try to update Restito verion to 0.4 and i got 0.51 java error.
Can you provide a release of newer versions compiled in java 6?
The dependency was downloaded using maven.

**Comment by mkotsur** [comment]
Hi Sandro,

Unfortunately it's not possible since I've started to use Java 7 features (e.g. diamonds). Since Java 6 has reached EOL a year ago, I don't think it makes sense not to use features of Java 7.
