### ISSUE TITLE
StubServer getters are not thread-safe

### ISSUE THREAD

**Issue by brendan-hofmann** [mkotsur/restito#33]
In the StubServer class, getStubs() and especially getCalls() are not thread safe, as they return the server's internal instance of those collections. Those methods should probably return copies of the collections instead, and you should use one of the thread-safe collection implementations that Java provides for the internal instances.

**Comment by mkotsur** [comment]
You are right. Although StubServer updates calls in thread-safe way, people can mess-up with them from the outside. Now its not possible anymore, callers will get read-only view of the lists.

**Comment by brendan-hofmann** [comment]
This still isn't  thread-safe. If those lists are updated while a client is iterating over them via the unmodifiable wrapper, a concurrent modification exception will still be thrown. You should be returning *copies* of the lists, in a thread-safe manner.

Unmodifiable collections are just wrapper proxies to the underlying collections. They do not perform any synchronization, nor do they have their own copies of the data. All they do is provide a read-only view of a collection.

Guava's ImmutableList actually does what you seem to think Collections.UnmodifiableList does.

Alternatively, instead of doing any synchronization of your own, you could just use one of the Concurrent collections implementations. You would then be able to safely return copies of those lists in the getters without worrying about multi-threading issues.

**Comment by mkotsur** [comment]
Ah, ok. Thanks for explaining. Now returning copies of lists, though would like to still keep them unmodifiable so that it's immediately clear that direct modification will have no effect anymore.

Have you bumped into this problem, or just found by looking through the code?

**Comment by brendan-hofmann** [comment]
We found this problem during usage, one of our tests was periodically failing.

Unfortunately this still isn't thread-safe. The ArrayList constructor access of the internal lists is not thread-safe, and the iteration over the stubs list is not thread-safe. I've submitted a pull request to address these issues.
