### ISSUE TITLE
Port selection is too random

### ISSUE THREAD

**Issue by driv** [mkotsur/restito#35]
From what I understand restito tries to start a server using `StubServer.DEFAULT_PORT` as port, if that port is not available it will try a higher port number. This is pretty clear in [SpecificVsRandomPortTest](https://github.com/mkotsur/restito/blob/master/src/test/java/guide/SpecificVsRandomPortTest.java).

I made a small test to reproduce the problem:

        System.out.println("Default port:" + StubServer.DEFAULT_PORT);;
        server = new StubServer().run();
        System.out.println("Port:" + server.getPort());
        server2 = new StubServer().run();
        System.out.println("Port2:" + server2.getPort());

And I get the following output:

    Default port:6666
    Port:14193
    Port2:23342

The problem is that in case of having to open the ports to be able to run the tests, I have no idea which ports to open, I thought that opening 6666-6766 would be enough.
Is the only solution in this case to generate each port manually? `6666 6667 6668...`

It would be nice to be able to set the default port and let it generate ports from that on.

**Comment by mkotsur** [comment]
I see your point. Now (in version 0.7) you can specify port range. Hope that helps.
