### ISSUE TITLE
Multiple requests frome the same server instance

### ISSUE THREAD

**Issue by danfran** [mkotsur/restito#37]
Hi, not sure if it's a bug or my misunderstanding:

I am trying to run in the same test 2 separate requests that should return different content:

```
whenHttp(server)
            .match(get('/something').parameter('par1', '1').parameter('par2', '2').withHeader('SOME-AUTH-TOKEN', AUTH_TOKEN))
            .then(
                contentType('text/csv'),
                stringContent("first content"),
                status(OK_200))

whenHttp(server)
            .match(get('/something').parameter('par1', '1').parameter('par2', '100').withHeader('SOME-AUTH-TOKEN', AUTH_TOKEN))
            .then(
                contentType('text/csv'),
                stringContent("second content"),
                status(OK_200))
```

When test runs two requests are created correctly (par2 only changes) but the content returned is always from the first successful request.

Am I doing something wrong or is it a bug?

Thanks!

**Comment by mkotsur** [comment]
Hey @danfran.

That should work. I tried to run simplified version of your test, with different GET parameters, and it passes.

I'm curious how do you actually check that it returns content from the first request? I'm using rest-assured for that in the example.

The code I've been using is:
```
    @Test
    public void shouldWork() {
        StubServer server1 = new StubServer().run();
        final Condition condition1 = Condition.uri("/something")
                .parameter("par1", "1")
                .parameter("par2", "2");


        final Condition condition2 = Condition.uri("/something")
                .parameter("par1", "1")
                .parameter("par2", "200");


        whenHttp(server1).match(condition1).then(
                contentType("text/csv"),
                stringContent("first content"),
                status(HttpStatus.OK_200)
        );
        whenHttp(server1).match(condition2).then(
                contentType("text/csv"),
                stringContent("second content"),
                status(HttpStatus.OK_200)
        );

        expect().content(containsString("first content")).when().get("http://localhost:" + server1.getPort() + "/something?par1=1&par2=2");
        expect().content(containsString("second content")).when().get("http://localhost:" + server1.getPort() + "/something?par1=1&par2=200");
    }
```

**Comment by danfran** [comment]
Still not luck.
On my service side I am using apache http client 4.5 to fetch data.
I have a "3 steps" flow.
The first one is a login that works.
The second one should fetch the first content but it always return the second content, event if the request has the URI of the first request.
Any idea?

This my current test (using Spock):

    def "authenticate and fetch data" () {

        given:
        StubServer server1 = new StubServer(SOME_PORT).run()

        final Condition condition1 = Condition.get('/something')
                .parameter('par1', '1')
                .parameter('par2', '1')
                .withHeader('X-AUTH-TOKEN', AUTH_TOKEN)


        final Condition condition2 = Condition.get('/something')
                .parameter('par1', '1')
                .parameter('par2', '100')
                .withHeader('X-AUTH-TOKEN', AUTH_TOKEN)

        when:
        whenHttp(server1).match(post('/login')).then(
                contentType('application/json'),
                stringContent("content with the token"),
                status(OK_200))

        whenHttp(server1).match(condition1).then(
                contentType('text/csv'),
                stringContent("some ad hoc content - one"),
                status(OK_200)
        )

        whenHttp(server1).match(condition2).then(
                contentType('text/csv'),
                stringContent("some ad hoc content - two"),
                status(OK_200)
        )

        service.fetch(SOME_PORT) // fetches in the first and second content

        then:
        // do some verifications here
    }

**Comment by danfran** [comment]
Ok I have found a work around. Using the condition like:

   final Condition condition1 = Condition.get('/something')
            .parameter('par1', '1')
            .parameter('par2', '1')
            .withHeader('X-AUTH-TOKEN', AUTH_TOKEN)

fails. It might be something related to Groovy, not sure about that.

Instead if I use something like:

whenHttp(server).match(uri('/something'), parameter('par1', '1'), parameter('par2', '1'), withHeader('X-AUTH-TOKEN', AUTH_TOKEN)).then(...)

it works.

**Comment by dobrowolskij** [comment]
In the mentioned at the beginning example two requests differ by query parameter. Is it possible to stub two exactly the same requests, so that each of them gives different response? I couldn't find anything.
Thanks

**Comment by mkotsur** [comment]
@dobrowolskij just to make sure I understand your question correctly: the requests are identical (including query parameters), but they should return different content based on their order. Is that it?

**Comment by dobrowolskij** [comment]
@mkotsur yes

**Comment by mkotsur** [comment]
@dobrowolskij it is *almost* possible :-) Couple of weeks ago we've started a discussion about this feature at PR #49 (which already contains a custom action implementation which you can already use) and then I've done some refactoring to have a better integration with the other APIs, and that is in PR #50.

I would be thankful to you if you can test/give feedback about the feature by building restito from the branch `shamoh-sequenced-stub-actions` (which represents PR #50), trying, and giving some feedback eventually. That would be great, then I can go on and release a new version.

One thing to know, though, it will work only on Java 8. Hope it's not a problem for you.

**Comment by mkotsur** [comment]
Closing due lack of activity...
