### ISSUE TITLE
Restito Certificate has expired for SSL

### ISSUE THREAD

**Issue by alcatwize** [mkotsur/restito#44]
When setting up a secured server, I get the following Java exception...

 javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateExpiredException: NotAfter: Thu Jan 24 06:30:07 CST 2013

**Comment by mkotsur** [comment]
@alcatwize thanks for reporting!

Could you share the code you're using? Is there something different from https://github.com/mkotsur/restito/blob/master/src/test/java/guide/UsingHttpsTest.java ? That test seems to still pass.

**Comment by mkotsur** [comment]
Hey, I've pushed new certificates (1cc1ae6). Could you build a snapshot of the `master` and check whether it solves your problem? I'm curious which client configuration you are using, because the certificates are self-signed anyway and this may still cause and exception.

**Comment by alcatwize** [comment]
Your new certificates work!! Thanks.  Your test example didn't catch it.  The apache client must not care about the date on the certificate.  I ran into problems when running our application in another VM and it would hit the new mocked out https endpoint and it complained about the date.  But, your new truststore_server & keystore_server files fixed the problem.  Thanks again for the quick response.

**Comment by alcatwize** [comment]
Will you be releasing a new version .9?

**Comment by mkotsur** [comment]
`0.8.1` should become available on nexus soon.
