### ISSUE TITLE
Stub and method toString()

### ISSUE THREAD

**Issue by jansyk13** [mkotsur/restito#45]
When calling method gotStubsCommitmentsDone() in EnsureHttp, in case of AssertionError the error message is not comprehensive. This makes testing and debugging hell.

Example:
<code>
"Expected stub com.xebialabs.restito.semantics.Stub@6a5f05f5 to be called 1 times, called 0 times instead"<code>

**Comment by mkotsur** [comment]
@jansyk13 good point. Would you make a PR for that?

**Comment by mkotsur** [comment]
I don't know if you guys are still interested, but now there is a solution! You can assign labels to stubs like this now:

```
whenHttp(server).match("Fancy stub", get("/neverHappens")).then(ok()).mustHappen();

ensureHttp(server).gotStubsCommitmentsDone();
```

Then the error message will be: 
`Expected stub Stub@6a5f05f5 [Fancy stub] to be called 1 times, called 0 times instead`

Any feedback is appreciated! /cc @jansyk13 @shamoh
