### ISSUE TITLE
Slow server response

### ISSUE THREAD

**Issue by davidsloan-eduserv** [mkotsur/restito#51]
Restito looks great and I was hoping to use it, however I was looking for a way to imitate a slow server response (or fixed delay, like WireMock allows).  This would be a very useful feature to add.

**Comment by mkotsur** [comment]
Hi @davidsloan-eduserv,

Thanks. Actually, I've answered a similar question on [SO](http://stackoverflow.com/questions/37076113/mockrestserviceserver-simulate-backend-timeout-in-integration-test) some time ago. As you are the second one who is asking about this feature, I'll add it as a standard action, and this will become available in the new version. In the meantime you could use the approach from the SO answer. I think the alpha version will be out pretty soon, within a week, or so...

By the way, as small survey if you don't mind :-) I've started using Java 8 features, which means that the new version will work on JDK8+. Is this ok with you?

**Comment by davidsloan-eduserv** [comment]
Hi Mike,
Thanks for the SO link!  I'm glad there's an approach.
Java 8 doesn't pose a problem, it's good to see libraries and frameworks taking advantage of the latest language features.

**Comment by mkotsur** [comment]
@davidsloan-eduserv Restito 0.8.2 with slow (configurable) responses is now available!
