### ISSUE TITLE
New 0.9.0 version does not automatically identity contentType if the XML or JSON file is too big

### ISSUE THREAD

**Issue by michelzanini** [mkotsur/restito#55]
Hi,

After 0.9.0 version, if you have a big XML file, and do a test like this:

```java
       whenHttp(server).
                match(endsWithUri("/demo")).
                then(resourceContent("big.xml"));

        expect().contentType(ContentType.XML).when().get("/demo");
```

The content type should be application/xml but it's empty!

On version 0.8.2 this works. Also, if the XML is small, it also works.
I figured if it's bigger then 300 lines or so, the problem start happening.
Not sure why is that.

Attaching an example project with failing tests to help.

This is a major problem for me.
Can you please fix and release a 0.9.1 version?

[content-type-issue.zip](https://github.com/mkotsur/restito/files/859719/content-type-issue.zip)

**Comment by michelzanini** [comment]
By the way, I think this might have being fixed by a fork in your repo:
https://github.com/leblonk/restito/commit/0f508fd1111cb289d2c084d9bdc0144fb7ba20ae

**Comment by mkotsur** [comment]
@michelzanini thanks for reporting this. It has been fixed by @leblonk and I have to release a new version. Apologies for not doing it earlier. Will let you know once it's there.

**Comment by michelzanini** [comment]
I can confirm 0.9.1 is released and fixes this issue.
I will close it now.

Thanks for the fast response and congratulations on the library, I am using it in several projects.
