### ISSUE TITLE
connection refused error.

### ISSUE THREAD

**Issue by mybostonstar** [mkotsur/restito#56]
We integrated entire restito as our mock framework and it is working fine. Suddenly we are seeing connection refused . Take as example that we have one mock service up and running /something. and first request send to mock , It is success . When we send second request. It send error saying connection refused.  Is this something new issue or something advice how we can handle this kind of error ?

**Comment by mkotsur** [comment]
Anything suspicious in the logs?

**Comment by mkotsur** [comment]
@mybostonstar Does it happen all the time, or sometimes? Some code or logs would be nice...

**Comment by mkotsur** [comment]
Feel free to reopen if you can provide more details.
