### ISSUE TITLE
resourceContent big files handling

### ISSUE THREAD

**Issue by SwEngin** [mkotsur/restito#57]
I have a response in xml file that's more than 700 lines and that specific request returns 500 error all the time

**Comment by mkotsur** [comment]
@SwEngin If there is 500 (server error) you probably see some exception in the logs. What exception is it?

**Comment by SwEngin** [comment]
No exceptions thrown from restito itself I just get the body as null and content type is not even set though the content length is correct so I get this: 
```
RESPONSE - [requestId=null, url=http://localhost:9999/service/resource/param, headers={Content-Length=[26614], Date=[Fri, 28 Jul 2017 12:15:47 GMT]}, body=null]
```

**Comment by mkotsur** [comment]
Ok, I'll try to reproduce, thanks.

**Comment by mkotsur** [comment]
Hey @SwEngin.

I've tested with a large file, didn't see any problems. I'd like to check if it's content-specific problem. Could you try to run it with [this file](https://github.com/mkotsur/restito/files/1185551/large-content.xml.zip) (unizp it first) and see if it still fails ..?

Does it still fail when you run a single test?

**Comment by SwEngin** [comment]
@mkotsur will test it

**Comment by SwEngin** [comment]
I tested with your file and still test fails

**Comment by mkotsur** [comment]
@SwEngin what OS / java version do you use?

**Comment by SwEngin** [comment]
@mkotsur I already found the problem. The problem is the the following:

```
public static byte[] getBytes(InputStream input) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] data = new byte[4096];

        int read;
        while((read = input.read(data, 0, data.length)) != -1) {
            buffer.write(data, 0, read);
        }

        buffer.flush();
        return buffer.toByteArray();
    }

```
You have a limit in your getBytes method, so the file is not completely read and of course that's a problem as the content can't be marshaled.That's version 0.9.0

If I use custom response like the following:

```
ClassLoader classLoader = getClass().getClassLoader();
File file = new File(classLoader.getResource("result.xml").getFile());
whenHttp(server).
                match(get("/service/resource/param1")).
                then(ok(), contentType("application/xml"),  custom((response) -> {
                    response.setContentLength((int) file.length());
                    try {
                        Files.copy(file, response.getOutputStream());
                        return response;
                    } catch (IOException var3) {
                        throw new RuntimeException("Can not write resource content for restito stubbing.");
                    }
 }));
```
the request succeeds.

**Comment by SwEngin** [comment]
And one more thing in this specific case the order of actions is important. So the contentType has to be set before the response is written.

**Comment by SwEngin** [comment]
I checked latest version and that was it the order of actions! :+1:
