### ISSUE TITLE
Severe encoding bug in Action.stringContent(String content).

### ISSUE THREAD

**Issue by garretwilson** [mkotsur/restito#66]
From looking at the code there appears to be a severe encoding bug in [`Action.stringContent(String content)`](https://mkotsur.github.io/restito/javadoc/current/com/xebialabs/restito/semantics/Action.html#stringContent-java.lang.String-).

```java
public static Action stringContent(final String content) {
  return bytesContent(content.getBytes());
}
```

You are simply retrieving the bytes of the string using `String.getBytes()` without indicating any encoding. `String.getBytes()` simply uses the system default charset which **you almost never want to do**. This will make code work differently on different platforms; moreover you won't be able to test what you want to test unless the charset just happens to match the one you expect. Tests shouldn't depend on luck.

There are two complementary ways to fix this:

* Have `Action.stringContent(final String content)` check to see if `Action.charset(Charset charset)` has been called, and if so, use that charset when retrieving the bytes (and if not preferably throw an exception to be _very explicit in the documentation the bad things that will happen if you don't specify a charset_). Note that it may not be possible to see if a charset has already been indicated, as the actions are independent; in this case, it would be best to remove this method altogether or highly discourage it (in which case people will still unwittingly use it).
* Add a `Action.stringContent(final String content, Charset charset)` method that provides a charset to use when retrieving the bytes of the string. This would be a convenience method that would also add an `Action.charset(Charset charset)`, much like `resourceContent(URL resourceUrl, Charset charset)` and the like already do.

It is absolutely crucial to add the latter method above. **Developers should not be using `content.getBytes()` in 99.9% of cases.**

**Comment by garretwilson** [comment]
As a workaround until the suggested method above is added, use:

```java
composite(charset(myCharset), bytesContent(myString.getBytes(myCharset)))
```

**Comment by mkotsur** [comment]
@garretwilson would you care to take a look at c6f269b?

**Comment by garretwilson** [comment]
Overall it looks good, I think. I'm not too familiar with REST Assured yet. I added a few comments on the tests.

Thanks for addressing this!

**Comment by mkotsur** [comment]
Will automatically become available with the next release.
